"""add metadata_column1

Revision ID: fc61056566c3
Revises: 8a96c8dea5c6
Create Date: 2026-09-22 11:36:29.258493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc61056566c3'
down_revision: Union[str, Sequence[str], None] = '8a96c8dea5c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('meta_data', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'meta_data')
    # ### end Alembic commands ###
